Search.appendIndex(
    [
                {
            "fqsen": "\\RNEClient\\CategoryCodes",
            "name": "CategoryCodes",
            "summary": "Class\u0020CategoryCodes",
            "url": "classes/RNEClient-CategoryCodes.html"
        },                {
            "fqsen": "\\RNEClient\\CategoryCodes\u003A\u003AprocessXlsxDataToJson\u0028\u0029",
            "name": "processXlsxDataToJson",
            "summary": "Process\u0020the\u0020category\u0020codes\u0020xlsx\u0020file\u0020to\u0020associative\u0020array",
            "url": "classes/RNEClient-CategoryCodes.html#method_processXlsxDataToJson"
        },                {
            "fqsen": "\\RNEClient\\CategoryCodes\u003A\u003AsaveJsonData\u0028\u0029",
            "name": "saveJsonData",
            "summary": "",
            "url": "classes/RNEClient-CategoryCodes.html#method_saveJsonData"
        },                {
            "fqsen": "\\RNEClient\\CategoryCodes\u003A\u003AgetCategoryCodes\u0028\u0029",
            "name": "getCategoryCodes",
            "summary": "",
            "url": "classes/RNEClient-CategoryCodes.html#method_getCategoryCodes"
        },                {
            "fqsen": "\\RNEClient\\RNEClient",
            "name": "RNEClient",
            "summary": "Class\u0020RNEClient",
            "url": "classes/RNEClient-RNEClient.html"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "RNEClient\u0020constructor.",
            "url": "classes/RNEClient-RNEClient.html#method___construct"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "Authentify\u0020the\u0020user\u0020and\u0020store\u0020the\u0020token\u0020in\u0020the\u0020client",
            "url": "classes/RNEClient-RNEClient.html#method_authenticate"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "Get\u0020the\u0020token",
            "url": "classes/RNEClient-RNEClient.html#method_getToken"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003AdecorateResponse\u0028\u0029",
            "name": "decorateResponse",
            "summary": "add\u0020a\u0020decoration\u0020to\u0020the\u0020response\nresultsCount,\u0020hasMoreResults,\u0020nextPageUrl",
            "url": "classes/RNEClient-RNEClient.html#method_decorateResponse"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003AgetAuthorizationHeaderArray\u0028\u0029",
            "name": "getAuthorizationHeaderArray",
            "summary": "Get\u0020the\u0020authorization\u0020header\u0020array",
            "url": "classes/RNEClient-RNEClient.html#method_getAuthorizationHeaderArray"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003AaddPageToUrl\u0028\u0029",
            "name": "addPageToUrl",
            "summary": "Add\u0020the\u0020page\u0020parameter\u0020to\u0020the\u0020url",
            "url": "classes/RNEClient-RNEClient.html#method_addPageToUrl"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003AaddPageSizeToUrl\u0028\u0029",
            "name": "addPageSizeToUrl",
            "summary": "Add\u0020the\u0020page\u0020size\u0020parameter\u0020to\u0020the\u0020url",
            "url": "classes/RNEClient-RNEClient.html#method_addPageSizeToUrl"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003ArequestApi\u0028\u0029",
            "name": "requestApi",
            "summary": "Request\u0020the\u0020API",
            "url": "classes/RNEClient-RNEClient.html#method_requestApi"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003AcatchResponseErrors\u0028\u0029",
            "name": "catchResponseErrors",
            "summary": "Catch\u0020the\u0020response\u0020errors",
            "url": "classes/RNEClient-RNEClient.html#method_catchResponseErrors"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003ADEFAULT_PAGE_SIZE",
            "name": "DEFAULT_PAGE_SIZE",
            "summary": "",
            "url": "classes/RNEClient-RNEClient.html#constant_DEFAULT_PAGE_SIZE"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003ABASE_URI",
            "name": "BASE_URI",
            "summary": "",
            "url": "classes/RNEClient-RNEClient.html#constant_BASE_URI"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003AVALID_ACTIVITY_SECTORS",
            "name": "VALID_ACTIVITY_SECTORS",
            "summary": "",
            "url": "classes/RNEClient-RNEClient.html#constant_VALID_ACTIVITY_SECTORS"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/RNEClient-RNEClient.html#property_client"
        },                {
            "fqsen": "\\RNEClient\\RNEClient\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/RNEClient-RNEClient.html#property_token"
        },                {
            "fqsen": "\\RNEClient\\RNEClientInterface",
            "name": "RNEClientInterface",
            "summary": "",
            "url": "classes/RNEClient-RNEClientInterface.html"
        },                {
            "fqsen": "\\RNEClient\\RNEClientInterface\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "authentication",
            "url": "classes/RNEClient-RNEClientInterface.html#method_authenticate"
        },                {
            "fqsen": "\\RNEClient\\RNEClientInterface\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "",
            "url": "classes/RNEClient-RNEClientInterface.html#method_getToken"
        },                {
            "fqsen": "\\RNEClient\\SearchCompanies",
            "name": "SearchCompanies",
            "summary": "Class\u0020SearchCompanies",
            "url": "classes/RNEClient-SearchCompanies.html"
        },                {
            "fqsen": "\\RNEClient\\SearchCompanies\u003A\u003AsearchBySiren\u0028\u0029",
            "name": "searchBySiren",
            "summary": "Search\u0020a\u0020company\u0020by\u0020its\u0020siren\u0020number\nExact\u0020search\u0020only",
            "url": "classes/RNEClient-SearchCompanies.html#method_searchBySiren"
        },                {
            "fqsen": "\\RNEClient\\SearchCompanies\u003A\u003AsearchByNationalDepositNumber\u0028\u0029",
            "name": "searchByNationalDepositNumber",
            "summary": "Search\u0020a\u0020single\u0020company\u0020by\u0020its\u0020national\u0020deposit\u0020number",
            "url": "classes/RNEClient-SearchCompanies.html#method_searchByNationalDepositNumber"
        },                {
            "fqsen": "\\RNEClient\\SearchCompanies\u003A\u003AsearchOldStateBySiren\u0028\u0029",
            "name": "searchOldStateBySiren",
            "summary": "Search\u0020a\u0020single\u0020company\u0020old\u0020state\u0020by\u0020its\u0020siren\u0020and\u0020date",
            "url": "classes/RNEClient-SearchCompanies.html#method_searchOldStateBySiren"
        },                {
            "fqsen": "\\RNEClient\\SearchCompanies\u003A\u003AsearchByMultipleSiren\u0028\u0029",
            "name": "searchByMultipleSiren",
            "summary": "Search\u0020companies\u0020by\u0020multiple\u0020siren\u0020numbers\nExact\u0020search\u0020only",
            "url": "classes/RNEClient-SearchCompanies.html#method_searchByMultipleSiren"
        },                {
            "fqsen": "\\RNEClient\\SearchCompanies\u003A\u003AsearchByName\u0028\u0029",
            "name": "searchByName",
            "summary": "Search\u0020companies\u0020by\u0020their\u0020name\nContains\u0020type\u0020search\u0020\u0028starts\u0020with,\u0020contains,\u0020ends\u0020with\u0029",
            "url": "classes/RNEClient-SearchCompanies.html#method_searchByName"
        },                {
            "fqsen": "\\RNEClient\\SearchCompanies\u003A\u003AsearchBySubmissionDate\u0028\u0029",
            "name": "searchBySubmissionDate",
            "summary": "Search\u0020a\u0020company\u0020by\u0020its\u0020submission\u0020dates\nsubmissionDateFrom\u0020\u0028included\u0029\u0020and\u0020submissionDateTo\u0020\u0028not\u0020included\u0029,\u0020at\u0020least\u0020from\u0020is\u0020required",
            "url": "classes/RNEClient-SearchCompanies.html#method_searchBySubmissionDate"
        },                {
            "fqsen": "\\RNEClient\\SearchCompanies\u003A\u003AsearchByActivitySector\u0028\u0029",
            "name": "searchByActivitySector",
            "summary": "Search\u0020companies\u0020by\u0020its\u0020activity\u0020sector",
            "url": "classes/RNEClient-SearchCompanies.html#method_searchByActivitySector"
        },                {
            "fqsen": "\\RNEClient\\SearchCompanies\u003A\u003AsearchByCategoryCode\u0028\u0029",
            "name": "searchByCategoryCode",
            "summary": "Search\u0020companies\u0020by\u0020its\u0020category\u0020code",
            "url": "classes/RNEClient-SearchCompanies.html#method_searchByCategoryCode"
        },                {
            "fqsen": "\\RNEClient\\SearchCompanies\u003A\u003AsearchByZipCode\u0028\u0029",
            "name": "searchByZipCode",
            "summary": "Search\u0020companies\u0020by\u0020its\u0020zip\u0020codes\nINPI\u0020DOCUMENTATION\u0020AMBIGUITY\u0020WARNING\u0020\u002D\u0020Seems\u0020to\u0020be\u0020a\u0020array\u0020of\u0020only\u0020one\u0020zip\u0020code\u0020\u0028issue\u0020with\u0020the\u0020INPI\u0020API\u0029\nIf\u0020multiple\u0020zip\u0020codes\u0020are\u0020provided\u0020to\u0020the\u0020API,\u0020results\u0020are\u0020not\u0020correct",
            "url": "classes/RNEClient-SearchCompanies.html#method_searchByZipCode"
        },                {
            "fqsen": "\\RNEClient\\SearchCompaniesInterface",
            "name": "SearchCompaniesInterface",
            "summary": "",
            "url": "classes/RNEClient-SearchCompaniesInterface.html"
        },                {
            "fqsen": "\\RNEClient\\SearchCompaniesInterface\u003A\u003AsearchBySiren\u0028\u0029",
            "name": "searchBySiren",
            "summary": "single\u0020company\u0020search",
            "url": "classes/RNEClient-SearchCompaniesInterface.html#method_searchBySiren"
        },                {
            "fqsen": "\\RNEClient\\SearchCompaniesInterface\u003A\u003AsearchByNationalDepositNumber\u0028\u0029",
            "name": "searchByNationalDepositNumber",
            "summary": "",
            "url": "classes/RNEClient-SearchCompaniesInterface.html#method_searchByNationalDepositNumber"
        },                {
            "fqsen": "\\RNEClient\\SearchCompaniesInterface\u003A\u003AsearchOldStateBySiren\u0028\u0029",
            "name": "searchOldStateBySiren",
            "summary": "",
            "url": "classes/RNEClient-SearchCompaniesInterface.html#method_searchOldStateBySiren"
        },                {
            "fqsen": "\\RNEClient\\SearchCompaniesInterface\u003A\u003AsearchByMultipleSiren\u0028\u0029",
            "name": "searchByMultipleSiren",
            "summary": "multiple\u0020companies\u0020search",
            "url": "classes/RNEClient-SearchCompaniesInterface.html#method_searchByMultipleSiren"
        },                {
            "fqsen": "\\RNEClient\\SearchCompaniesInterface\u003A\u003AsearchByName\u0028\u0029",
            "name": "searchByName",
            "summary": "",
            "url": "classes/RNEClient-SearchCompaniesInterface.html#method_searchByName"
        },                {
            "fqsen": "\\RNEClient\\SearchCompaniesInterface\u003A\u003AsearchBySubmissionDate\u0028\u0029",
            "name": "searchBySubmissionDate",
            "summary": "",
            "url": "classes/RNEClient-SearchCompaniesInterface.html#method_searchBySubmissionDate"
        },                {
            "fqsen": "\\RNEClient\\SearchCompaniesInterface\u003A\u003AsearchByActivitySector\u0028\u0029",
            "name": "searchByActivitySector",
            "summary": "",
            "url": "classes/RNEClient-SearchCompaniesInterface.html#method_searchByActivitySector"
        },                {
            "fqsen": "\\RNEClient\\SearchCompaniesInterface\u003A\u003AsearchByCategoryCode\u0028\u0029",
            "name": "searchByCategoryCode",
            "summary": "",
            "url": "classes/RNEClient-SearchCompaniesInterface.html#method_searchByCategoryCode"
        },                {
            "fqsen": "\\RNEClient\\SearchCompaniesInterface\u003A\u003AsearchByZipCode\u0028\u0029",
            "name": "searchByZipCode",
            "summary": "",
            "url": "classes/RNEClient-SearchCompaniesInterface.html#method_searchByZipCode"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\RNEClient",
            "name": "RNEClient",
            "summary": "",
            "url": "namespaces/rneclient.html"
        }            ]
);
